name: aurora
description: "A B2B marketplace for sellers and factories."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.12.4
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  shared_preferences: ^2.3.5
  provider: ^6.1.5
  vault_analog: ^4.0.0
  image_picker: ^1.2.2
  debug_print: ^0.0.1+1
  flutter_analog: ^5.1.0
  cached_network_image: ^3.4.1
  flutter_ri verpod: ^2.6.1
  riverpod_annotation: ^2.6.1

flutter:
  uses-material-design: true
  generate: true